name: Glow
description: "Glow: an energy tracker for your home"
paginate: 10
permalink: pretty
gems: [jekyll-paginate]

collections:
  faq:
    output: true
    permalink: /:collection/:path/
    title: FAQ
    layout: faq
