name: Glow
description: "Glow: an energy tracker for your home"
paginate: 10
gems: [jekyll-paginate]
permalink: pretty

collections:
  faq:
    output: true
    permalink: /:collection/:path/
    title: FAQ
    layout: faq
